package:
  name: menuinst
  version: 1.3.2.1

source:
    fn: menuinst-1.3.2.1.tar.bz2
    url: http://pappel.iisb.fraunhofer.de/foxbms/conda/src/menuinst-1.3.2.1.tar.bz2


requirements:
  build:
    - python
  run:
    - python


