package:
  name: menuinst
  version: 1.3.2.2

source:
    fn: menuinst-1.3.2+8.ga8f6f8a.dirty.tar.gz
    url: http://pappel.iisb.fraunhofer.de/foxbms/conda/src/menuinst-1.3.2+8.ga8f6f8a.dirty.tar.gz


requirements:
  build:
    - python
    - pywin32 #[win]
  run:
    - python


