
package:
    name: breathe
    version: 4.0.6

source:
    git_url: https://github.com/michaeljones/breathe
    git_ref: v4.6.0

build:
    number: 0

requirements:
    build:
        - python
        - docutils
        - sphinx

    run:
        - python
        - docutils
        - sphinx
        - doxygen

test:
    imports:
        - breathe

    #commands:
    #    - make

about:
    home: http://michaeljones.github.io/breathe/
    license: BSD

