package:
    name: doxygen
    version: "1.8.10"

source:
    git_ref: Release_1_8_10 # [osx]
    git_ref: Release_1_8_10 # [linux]
    git_url: https://github.com/doxygen/doxygen # [osx]
    git_url: https://github.com/doxygen/doxygen # [linux]
    fn: doxygen-1.8.10.windows.x64.bin.zip   # [win]
    url: http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.windows.x64.bin.zip # [win]
    # why not use github release?; why not use same methode as for linux/osx?
    # https://github.com/doxygen/doxygen/archive/Release_1_8_13.zip
    # https://github.com/doxygen/doxygen/archive/Release_1_8_13.tar.gz


requirements:
    build:
       - cmake
       - bison # [linux]
       - flex # [linux]
       - m4 # [linux]

build:
    number: 1
    number: 2 # [linux]

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: http://doxygen.org
    license: "GPL"
    summary: "Generate documentation from source code"
