package:
    name: flex
    version: 2.6.4

source:
    git_url: https://github.com/westes/flex/tags # [linux]
    git_ref: v2.6.4 # [linux]


about:
  home: http://flex.sourceforge.net/
  license: BSD
