package:
    name: foxbms
    version: 0.7

source:
    git_url: sourcegate:/home/data/gitroot/foxbms/foxbms-frontdesk.git

build:
    number: 1
    osx_is_app: True
    entry_points:
        - foxconfig = foxbms.configure:main
        - foxygen = foxbms.foxygen:main
        - fbterminal = foxbms.fbterminal:main
        - foxbms = foxbms.foxfdd:main #[not win]

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - wxpython
        - docutils
        - foxbmsflashtool
        - pyyaml
        - appdirs
        - git
        - gcc-arm-none-eabi
        - doxygen
        - breathe
        - sphinx

about:
    home: http://www.foxbms.org
    license: BSD
    license_file: LICENSE

