#
# file:        meta.yaml
# date:        Mon Aug 17 16:04:15 CEST 2015
# author:      Tim Fuehner <tim.fuehner@iisb.fraunhofer.de>
#
# Repackaging of gcc-arm
# $Id$
#

package:
  name: gcc-arm-none-eabi
  version: 6-2017-q2-update

source:
  fn: gcc-arm-none-eabi-6-2017-q2-update-win32.zip      # [win]
  fn: gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2  # [linux]
  fn: gcc-arm-none-eabi-6-2017-q2-update-mac.tar.bz2    # [osx]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-win32.zip       # [win]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2   # [linux]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-mac.tar.bz2     # [osx]
  md5: df6c2f763a6114c951e3f1e509af3cbc   # [win]
  md5: 13747255194398ee08b3ba42e40e9465   # [linux]
  md5: d536d7fb167c04b24f7f0d40cd739cac   # [osx]

about:
  home:    https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
  license: GPL
