package:
  name: cmake
  version: 3.3.0

source:
  fn: cmake-3.3.0.tar.gz # [osx]
  fn: cmake-3.3.0.tar.gz # [linux]
  fn: cmake-3.2.3-win32-x86.zip  # [win]
  url: http://www.cmake.org/files/v3.3/cmake-3.3.0.tar.gz # [osx]
  url: http://www.cmake.org/files/v3.3/cmake-3.3.0.tar.gz # [linux]
  url: http://www.cmake.org/files/v3.2/cmake-3.2.3-win32-x86.zip # [win]
  md5: b1d4823e3f74c961486d9f253da9825d # [osx]

test:
  commands:
    - cmake --help # [osx]
    - cmake --help # [linux]

about:
  home: http://www.cmake.org/
  license: BSD
