package:
  name: cmake
  version: 3.3.0

source:
  fn: cmake-3.9.0.tar.gz # [osx]
  fn: cmake-3.9.0.tar.gz # [linux]
  fn: cmake-3.9.0-win64-x64.zip # [win]
  url: http://www.cmake.org/files/v3.9/cmake-3.9.0.tar.gz # [osx]
  url: http://www.cmake.org/files/v3.9/cmake-3.9.0.tar.gz # [linux]
  url: http://www.cmake.org/files/v3.9/cmake-3.9.0-win64-x64.zip # [win]
  # md5: b1d4823e3f74c961486d9f253da9825d # [osx]

test:
  commands:
    - cmake --help # [osx]
    - cmake --help # [linux]
    - cmake --help # [win]

about:
  home: http://www.cmake.org/
  license: BSD
