package:
    name: foxbmsflashtool
    version: 0.3

source:
    git_url: https://github.com/foxBMS/foxBMS-flashtool

build:
    number: 1
    osx_is_app: True
    entry_points:
        - inari = foxbmsflashtool.inari:main
        - fbflasher = foxbmsflashtool.loader:main

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - wxpython
        - pyserial 3.0.1
        - bitstring

about:
    home: http://www.foxbms.org
    license: BSD
    license_file: LICENSE.md
    summary: foxBMS flash tools, including a command line and a GUI tool

