package:
  name: git
  version: 2.5.0

source:
  git_url: https://github.com/git/git.git # [osx]
  git_tag: v2.5.0 # [osx]
  url: https://www.kernel.org/pub/software/scm/git/git-2.5.0.tar.xz # [linux]
  fn: git-2.5.0.tar.xz # [linux]
  fn: PortableGit-2.5.0-64-bit.7z.exe # [win]
  url: https://github.com/git-for-windows/git/releases/download/v2.5.0.windows.1/PortableGit-2.5.0-64-bit.7z.exe # [win]

requirements:
  build:
    - openssl
    - zlib
  run:
    - openssl
    - zlib

test:
  commands:
    - git --version # [osx]
    - git --version # [linux]

about:
  home: https://git-scm.com/
  license: GPL v2 and LGPL 2.1
  summary: distributed version control system
