def configure(conf):
    conf.find_program('pyinstaller', var="PYINSTALLER")
    if not conf.env.PYINSTALLER:
        conf.fatal('could not find the program pyinstaller')

def build(bld):
    '''
    for x in ['LICENSE-ANACONDA.txt', 'install.py']:
        bld(rule = 'cp ${SRC} ${SRC[0].parent.abspath(env)}/${SRC[0].name}', source = x)
    '''
    tg = bld(rule='${PYINSTALLER} -c -y --onefile ${SRC[0].abspath()}', source='INSTALL.spec', target='dist/foxcondainstall')

